name: validate
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v2

      - name: 💾 Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: ⎔ Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: 📀 Install dependencies
        run: npm install

      - name: 🧹 Lint
        run: npm run lint

      - name: 😍 Prettier check
        run: npm run check

      - name: 🧪 Test
        run: npm run coverage

      - name: ⏫ Upload coverage
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: 👷‍♀️ Build
        run: npm run build -- --prod

      - name: ⏫ Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: |
            build
